# Generated by Django 4.0.4 on 2022-04-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0002_sortie_utilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itineraire',
            old_name='Nom de la sortie',
            new_name='titre',
        ),
    ]
