# Generated by Django 4.0.4 on 2022-04-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0003_rename_nom de la sortie_itineraire_titre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itineraire',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='itineraire',
            old_name='Durée estimée (en h)',
            new_name='duree_estime',
        ),
        migrations.RenameField(
            model_name='itineraire',
            old_name='Point de départ',
            new_name='point_de_depart',
        ),
        migrations.RenameField(
            model_name='sortie',
            old_name='Durée réelle (en h)',
            new_name='duree_reelle',
        ),
    ]
