# Generated by Django 4.0.4 on 2022-04-20 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0004_rename_description_itineraire_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraire',
            name='altitude_de_depart',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='altitude_max',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='altitude_min',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='denivele_negatif_cumule',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='denivele_positif_cumule',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='duree_estime',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='duree_reelle',
            field=models.DurationField(),
        ),
    ]
