# Generated by Django 4.0.4 on 2022-04-20 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0006_alter_itineraire_duree_estime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='duree_reelle',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(3)]),
        ),
    ]
