# Generated by Django 4.0.4 on 2022-04-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0008_alter_itineraire_duree_estime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraire',
            name='description',
            field=models.TextField(),
        ),
    ]
