# Generated by Django 4.0.4 on 2022-04-21 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0009_alter_itineraire_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='experience_groupe',
            field=models.CharField(choices=[('bonne', 'bonne'), ('moyenne', 'moyenne'), ('mauvaise', 'mauvaise')], default='bonne', max_length=200),
        ),
        migrations.AddField(
            model_name='sortie',
            name='nombre_participant',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
