# Generated by Django 4.0.4 on 2022-04-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0010_sortie_experience_groupe_sortie_nombre_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='meteo',
            field=models.CharField(choices=[('bonne', 'bonne'), ('moyenne', 'moyenne'), ('mauvaise', 'mauvaise')], default='bonne', max_length=200),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='experience_groupe',
            field=models.CharField(choices=[('debutants', 'debutants'), ('tous expérimentés', 'tous expérimentés'), ('mixte', 'mixte')], default='mixte', max_length=200),
        ),
    ]
